# Generated by Django 3.2.4 on 2021-07-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('grado', models.IntegerField()),
                ('grupo', models.CharField(max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha última actualización')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-create_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['-create_at'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.TextField(verbose_name='Clave')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('correo', models.TextField(verbose_name='Correo electrónico')),
                ('password', models.TextField(verbose_name='Contraseña')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha última actualización')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.grupo', verbose_name='Grupo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.rol', verbose_name='Tipo de cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-create_at'],
            },
        ),
    ]
