# Generated by Django 3.2.4 on 2021-07-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20210710_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(max_length=2, verbose_name='Grado/grupo'),
        ),
    ]
