# Generated by Django 3.2.4 on 2021-07-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_cuenta_paterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='materno',
            field=models.TextField(default='Example', verbose_name='Apellido materno'),
        ),
    ]
