# Generated by Django 3.2.4 on 2021-08-20 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_rename_descripción_rol_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha última actualización')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Duda',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_usuario', models.TextField(verbose_name='ID usuario')),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Respuesta')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha última actualización')),
                ('ID_duda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.duda', verbose_name='Id Duda')),
            ],
        ),
    ]
