# Generated by Django 3.2.4 on 2021-07-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_auto_20210710_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='grado',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(max_length=2),
        ),
    ]
