# Generated by Django 3.2.4 on 2021-07-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_cuenta_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='paterno',
            field=models.TextField(verbose_name='Apellido paterno'),
        ),
    ]
