# Generated by Django 3.2.4 on 2021-07-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_alter_cuenta_materno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
