# Generated by Django 3.2.4 on 2021-08-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0011_auto_20210820_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='duda',
            name='contenido',
            field=models.TextField(default='Contenido', verbose_name='Contenido de la publicación'),
            preserve_default=False,
        ),
    ]
