# Generated by Django 3.2.4 on 2021-08-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0013_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='ID_usuario',
            field=models.TextField(default='00', verbose_name='Id usuario'),
            preserve_default=False,
        ),
    ]
