# Generated by Django 3.2.4 on 2021-08-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0015_alter_respuesta_id_duda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='ID_duda',
            field=models.IntegerField(verbose_name='Id Duda'),
        ),
    ]
