# Generated by Django 3.2.4 on 2021-08-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0017_respuesta_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='duda',
            name='nombre_usuario',
            field=models.TextField(default='nombre', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
