# Generated by Django 3.2.4 on 2021-08-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0018_duda_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ID_profsor',
            field=models.TextField(default='text', verbose_name='ID profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombre_profesor',
            field=models.TextField(default='text', verbose_name='Profesor'),
            preserve_default=False,
        ),
    ]
