# Generated by Django 3.2.4 on 2021-08-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0019_auto_20210823_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='ID_profsor',
            new_name='ID_profesor',
        ),
    ]
