# Generated by Django 3.2.4 on 2021-08-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0021_entrega_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='actividad',
            field=models.TextField(default='Activity', verbose_name='Actividad'),
            preserve_default=False,
        ),
    ]
