# Generated by Django 3.2.4 on 2021-08-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0022_entrega_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='id_actividad',
            field=models.IntegerField(),
        ),
    ]
